# Generated by Django 4.2.5 on 2023-10-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_item',
            name='tax',
            field=models.FloatField(),
        ),
    ]
