# Generated by Django 4.2.5 on 2023-10-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_alter_invoice_item_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='estimate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
