# Generated by Django 4.2.5 on 2023-10-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_invoice_bank_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_item',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice_item',
            name='paid_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
