# Generated by Django 4.2.5 on 2023-10-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_invoice_estimate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_item',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='invoice_item',
            name='paid_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
