# Generated by Django 4.2.5 on 2023-10-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_invoice_item_balance_invoice_item_paid_amount'),
        ('zohoapp', '0004_remove_invoice_item_balance_and_more'),
        ('zohoapp', '0019_auto_20230927_0903'),
    ]

    operations = [
    ]
